/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-16.glb -T 
Files: macbook-16.glb [639.28KB] > C:\Users\lasis\OneDrive\Documentos\SAAS\macbook_gsap_app\public\models\macbook-16-transformed.glb [629.72KB] (1%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import React, { useEffect, useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import useMacbookStore from "../../store";
import {noChangeParts} from "../../constants/index.js"
import { MeshBasicMaterial } from 'three'

export default function MacbookModel16(props) {
  
  const { scene } = useGLTF('/models/macbook-16-transformed.glb');
  const color = useMacbookStore((state) => state.color);

  const texture = useTexture('/screen.png');
  const screenMaterial = useMemo(() => new MeshBasicMaterial({ map: texture }), [texture]);

  const modelScene = useMemo(() => scene.clone(true), [scene]);

  useEffect(() => {
    modelScene.traverse((child) => {
      if (!child.isMesh) return;

      // Keep the screen textured (and not recolored).
      if (child.name === 'Object_123') {
        if (!child.userData.screenMaterialApplied) {
          child.material = screenMaterial;
          child.userData.screenMaterialApplied = true;
        }
        return;
      }

      if (noChangeParts.includes(child.name)) return;

      const materialList = Array.isArray(child.material) ? child.material : [child.material];

      if (!child.userData.materialCloned) {
        const cloned = materialList.map((material) => material?.clone?.() ?? material);
        child.material = Array.isArray(child.material) ? cloned : cloned[0];
        child.userData.materialCloned = true;
      }

      const activeMaterials = Array.isArray(child.material) ? child.material : [child.material];
      activeMaterials.forEach((material) => {
        if (!material?.color) return;
        material.color.set(color);
        material.needsUpdate = true;
      });
    });
  }, [color, modelScene, screenMaterial]);

  return (
    <primitive object={modelScene} dispose={null} {...props} />
  )
}

useGLTF.preload('/models/macbook-16-transformed.glb')
